### ISSUE TITLE
Unclear whether error or total state KF

### ISSUE THREAD

**Issue by jtec** [andreabelles/Time-Synch#4]
In standardEKF.m, the update corrects the total state, even if the correction is called "xEst". So is looks like a total state EKF has been implemented, using IMU observations to propagate the mean? Please make the distinction clear in the report.

**Comment by andreabelles** [comment]
From 2008 and 2011 papers, we can see that they implement an error-state KF to estimate position, velocity (etc.) errors and then they use this error to correct the IMU position. Therefore, we tried to follow the same notation and structure as they. However, in the end, we realized that our state is defined by the mechanization equations (a total state) and we use the GNSS measurements to correct this position, so the Q matrix refers to the covariances associated with IMU sensors.  
Maybe we can change the name of the variables according to this interpretation of a total-state KF instead of following the notation of the papers, which may be a bit more confusing.

**Comment by jtec** [comment]
OK - when it comes to notation, the tutorial by Solà is very good and clear, see e.g. Table 3 in 

https://teams.microsoft.com/l/file/4F1D9569-05A5-4DF7-9DB1-74E90ABB828C?tenantId=0ddba9e7-c2fd-4665-a6bf-4eb37e23d129&fileType=pdf&objectUrl=https%3A%2F%2Fenacfr.sharepoint.com%2Fsites%2FImpactofSensorTimingErrorsonanIntegratedNavigationFilterforR%2FDocuments%20partages%2FGeneral%2Fliterature%2F%5BSol%C3%A0%2C%202017%5D%20Quaternion%20kinematics%20for%20the%20error-state%20Kalman%20filter.pdf&baseUrl=https%3A%2F%2Fenacfr.sharepoint.com%2Fsites%2FImpactofSensorTimingErrorsonanIntegratedNavigationFilterforR&serviceName=teams&threadId=19:eb15cd9fe41b4be79fca4772620173d5@thread.tacv2&groupId=f758c516-29df-4171-a30d-d5d8b0195246
